#! /bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
nitrogen --restore &
picom --experimental-backends -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a discord desktop='^5' follow=on
bspc rule -a mailspring desktop='^4' follow=on
bspc rule -a mpv state=floating
bspc rule -a Htop state=floating
bspc rule -a thunar desktop='^3' follow=on
bspc rule -a Pamix-git state=floating
bspc rule -a Galculator state=floating
bspc rule -a Screenkey manage=off
